'use client';

import Link from 'next/link';
import { useState, type FormEvent } from 'react';
import { AppIcon } from '@/components/ui/app-icon';
import { useCompanyLoans } from '@/hooks/use-company-loans';
import { useCompanyTransactions } from '@/hooks/use-company-transactions';
import { useCurrentAppRecords } from '@/hooks/use-current-app-records';
import { useAppTranslation } from '@/hooks/use-app-translation';
import { getCompanyBalance, getCompanyLoanSnapshots, getTotalLoanOutstanding, isCompanyDebit, type CompanyLoanSnapshot } from '@/lib/calculations/company-balance';
import { addCompanyLoan, addCompanyLoanRepayment, addCompanyTransaction, deleteCompanyTransaction } from '@/lib/database/repository';
import { formatCurrency } from '@/lib/formatting/currency';
import { formatDate, getLocalDateValue } from '@/lib/formatting/date';
import type { CompanyTransaction, CompanyTransactionType } from '@/types/domain';

const transactionLabels: Record<CompanyTransactionType, string> = { credit: 'Company credit', withdrawal: 'Withdrawal', voucher: 'Voucher', advance: 'Advance', loan: 'Loan issued', 'loan-repayment': 'Loan repayment', deduction: 'Deduction' };
const manualTransactionTypes = ['credit', 'withdrawal', 'voucher', 'advance', 'deduction'] as const;
type ManualCompanyTransactionType = typeof manualTransactionTypes[number];

export function CompanyContent() {
  const { t } = useAppTranslation();
  const { isLoading, isOnboarded } = useCurrentAppRecords();
  const { transactions, isLoading: transactionsLoading } = useCompanyTransactions();
  const { loans, isLoading: loansLoading } = useCompanyLoans();
  if (isLoading || transactionsLoading || loansLoading) return <section className="dashboard-loading" aria-live="polite">{t('loadingCompany')}</section>;
  if (!isOnboarded) return <SetupRequired />;

  const balance = getCompanyBalance(transactions);
  const credits = transactions.filter((transaction) => !isCompanyDebit(transaction.type)).reduce((total, transaction) => total + transaction.amount, 0);
  const debits = transactions.filter((transaction) => isCompanyDebit(transaction.type)).reduce((total, transaction) => total + transaction.amount, 0);
  const loanSnapshots = getCompanyLoanSnapshots(loans, transactions);
  const outstandingLoans = getTotalLoanOutstanding(loans, transactions);
  return <section className="company-page"><header className="page-heading"><div><p className="eyebrow">COMPANY LEDGER</p><h1>Know what&apos;s outstanding.</h1><p className="page-subtitle">Log company movements and track each loan repayment locally. Totals always come from the full record.</p></div></header><section className="company-balance-card"><div><p className="eyebrow">CURRENT COMPANY BALANCE</p><strong className={balance < 0 ? 'balance-negative' : ''}>{formatCurrency(balance)}</strong><p>{balance >= 0 ? 'Available company credit' : 'Company deductions exceed credits'}</p></div><span className="local-pill"><span className="pulse-dot" />Local ledger</span></section><div className="company-summary"><SummaryCard label="Credits" amount={credits} tone="credit" /><SummaryCard label="Deductions" amount={debits} tone="debit" /><SummaryCard label="Loans due" amount={outstandingLoans} tone="debit" /><SummaryCard label="Entries" amount={transactions.length} tone="neutral" /></div><LoanPanel loans={loanSnapshots} /><div className="company-layout"><TransactionForm /><TransactionList transactions={transactions} /></div></section>;
}

function LoanPanel({ loans }: { loans: CompanyLoanSnapshot[] }) {
  const [name, setName] = useState(''); const [principalAmount, setPrincipalAmount] = useState(''); const [issuedOn, setIssuedOn] = useState(getLocalDateValue); const [note, setNote] = useState(''); const [status, setStatus] = useState(''); const [isSaving, setIsSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const amount = Number(principalAmount); if (!Number.isFinite(amount) || amount <= 0) { setStatus('Enter a principal amount greater than zero.'); return; } setIsSaving(true); setStatus(''); try { await addCompanyLoan({ name: name.trim(), principalAmount: amount, issuedOn, note: note.trim() }); setName(''); setPrincipalAmount(''); setNote(''); setStatus('Loan issued and saved in the company ledger.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Could not save the loan.'); } finally { setIsSaving(false); } };
  return <section className="loan-section"><div className="panel-heading"><div><p className="eyebrow">LOAN TRACKER</p><h2>Issue and settle company loans.</h2></div><span className="progress-label">{loans.filter((loan) => !loan.isSettled).length} open</span></div><div className="loan-layout"><form className="loan-form" onSubmit={submit}><p>Issuing a loan creates a linked debit in the company ledger. Repayments can never exceed the remaining principal.</p><label className="field"><span>Loan name</span><input maxLength={60} value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Laptop advance" required /></label><div className="form-grid compact-form-grid"><label className="field"><span>Principal (PKR)</span><input type="number" min="1" inputMode="decimal" value={principalAmount} onChange={(event) => setPrincipalAmount(event.target.value)} placeholder="0" required /></label><label className="field"><span>Issue date</span><input type="date" value={issuedOn} onChange={(event) => setIssuedOn(event.target.value)} required /></label></div><label className="field"><span>Note</span><input maxLength={140} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional explanation" /></label><div className="editor-actions"><span role="status">{status}</span><button className="primary-button" type="submit" disabled={isSaving}>{isSaving ? 'Saving…' : 'Issue loan'} <AppIcon name="plus" aria-hidden="true" size={17} /></button></div></form><div className="loan-list">{loans.length ? loans.map((loan) => <LoanCard key={loan.id} loan={loan} />) : <div className="ledger-empty"><AppIcon name="building" aria-hidden="true" size={24} /><p>No tracked loans yet.</p><span>Issue a company loan to track its outstanding amount and repayments.</span></div>}</div></div></section>;
}

function LoanCard({ loan }: { loan: CompanyLoanSnapshot }) {
  const [amount, setAmount] = useState(''); const [occurredOn, setOccurredOn] = useState(getLocalDateValue); const [note, setNote] = useState(''); const [status, setStatus] = useState(''); const [isSaving, setIsSaving] = useState(false); const progress = Math.round((loan.repaidAmount / loan.principalAmount) * 100);
  const repay = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const parsedAmount = Number(amount); if (!Number.isFinite(parsedAmount) || parsedAmount <= 0) { setStatus('Enter a repayment amount greater than zero.'); return; } setIsSaving(true); setStatus(''); try { await addCompanyLoanRepayment({ loanId: loan.id, amount: parsedAmount, occurredOn, note: note.trim() }); setAmount(''); setNote(''); setStatus('Repayment saved.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Could not save the repayment.'); } finally { setIsSaving(false); } };
  return <article className="loan-card"><div className="loan-card-heading"><div><strong>{loan.name}</strong><small>Issued {formatDate(loan.issuedOn)}</small></div><span className={loan.isSettled ? 'loan-settled' : 'loan-open'}>{loan.isSettled ? 'Settled' : 'Open'}</span></div><div className="loan-amounts"><span>Outstanding <b>{formatCurrency(loan.outstandingAmount)}</b></span><span>Repaid <b>{formatCurrency(loan.repaidAmount)}</b></span></div><progress value={loan.repaidAmount} max={loan.principalAmount}>{progress}%</progress><small className="loan-progress">{progress}% repaid of {formatCurrency(loan.principalAmount)}</small>{loan.note ? <p>{loan.note}</p> : null}{!loan.isSettled ? <form className="loan-repayment-form" onSubmit={repay}><div className="form-grid compact-form-grid"><label className="field"><span>Repayment (PKR)</span><input type="number" min="1" max={loan.outstandingAmount} inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} required /></label><label className="field"><span>Date</span><input type="date" value={occurredOn} onChange={(event) => setOccurredOn(event.target.value)} required /></label></div><label className="field"><span>Note</span><input maxLength={140} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional repayment note" /></label><div className="editor-actions"><span role="status">{status}</span><button className="secondary-button" type="submit" disabled={isSaving}>{isSaving ? 'Saving…' : 'Record repayment'}</button></div></form> : null}</article>;
}

function TransactionForm() { const [type, setType] = useState<ManualCompanyTransactionType>('credit'); const [amount, setAmount] = useState(''); const [occurredOn, setOccurredOn] = useState(getLocalDateValue); const [note, setNote] = useState(''); const [status, setStatus] = useState(''); const [isSaving, setIsSaving] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const parsedAmount = Number(amount); if (!Number.isFinite(parsedAmount) || parsedAmount <= 0) { setStatus('Enter an amount greater than zero.'); return; } setIsSaving(true); setStatus(''); try { await addCompanyTransaction({ type, amount: parsedAmount, occurredOn, note: note.trim() }); setAmount(''); setNote(''); setStatus('Entry saved locally.'); } catch { setStatus('Could not save this entry locally. Please try again.'); } finally { setIsSaving(false); } }; return <section className="company-entry-form"><div><p className="eyebrow">NEW ENTRY</p><h2>Record another movement.</h2><p>Use the loan tracker above for loans and repayments. Credits increase balance; these other entries reduce it.</p></div><form onSubmit={submit}><label className="field"><span>Entry type</span><select value={type} onChange={(event) => setType(event.target.value as ManualCompanyTransactionType)}>{manualTransactionTypes.map((value) => <option value={value} key={value}>{transactionLabels[value]}</option>)}</select></label><div className="form-grid compact-form-grid"><label className="field"><span>Amount (PKR)</span><input type="number" min="1" inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0" required /></label><label className="field"><span>Date</span><input type="date" value={occurredOn} onChange={(event) => setOccurredOn(event.target.value)} required /></label></div><label className="field"><span>Note</span><input maxLength={140} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional reference or explanation" /></label><div className="editor-actions"><span role="status">{status}</span><button className="primary-button" type="submit" disabled={isSaving}>{isSaving ? 'Saving…' : 'Add entry'} <AppIcon name="plus" aria-hidden="true" size={17} /></button></div></form></section>; }
function TransactionList({ transactions }: { transactions: CompanyTransaction[] }) { const [removingId, setRemovingId] = useState<string | null>(null); const remove = async (transaction: CompanyTransaction) => { const warning = transaction.type === 'loan' && transaction.loanId ? ' This also removes its repayment history.' : ''; if (!window.confirm(`Remove the ${transactionLabels[transaction.type].toLowerCase()} from ${formatDate(transaction.occurredOn)}?${warning}`)) return; setRemovingId(transaction.id); try { await deleteCompanyTransaction(transaction.id); } finally { setRemovingId(null); } }; return <section className="company-transaction-list"><div className="panel-heading"><div><p className="eyebrow">LEDGER</p><h2>Recent activity</h2></div><span className="progress-label">{transactions.length} total</span></div>{transactions.length ? <ul>{transactions.map((transaction) => { const isDebit = isCompanyDebit(transaction.type); return <li key={transaction.id}><span className={`transaction-type transaction-${transaction.type}`}>{transactionLabels[transaction.type]}</span><div><strong>{transaction.note || 'No note added'}</strong><small>{formatDate(transaction.occurredOn)}</small></div><b className={isDebit ? 'transaction-debit' : 'transaction-credit'}>{isDebit ? '−' : '+'}{formatCurrency(transaction.amount)}</b><button className="remove-button" type="button" disabled={removingId === transaction.id} onClick={() => remove(transaction)} aria-label={`Remove ${transactionLabels[transaction.type]} entry`}>{removingId === transaction.id ? '…' : 'Remove'}</button></li>; })}</ul> : <div className="ledger-empty"><AppIcon name="building" aria-hidden="true" size={24} /><p>No company entries yet.</p><span>Add a credit, deduction, or tracked loan to begin.</span></div>}</section>; }
function SummaryCard({ label, amount, tone }: { label: string; amount: number; tone: 'credit' | 'debit' | 'neutral' }) { return <article><span>{label}</span><strong className={tone === 'credit' ? 'transaction-credit' : tone === 'debit' ? 'transaction-debit' : ''}>{label === 'Entries' ? amount : formatCurrency(amount)}</strong><small>{tone === 'credit' ? 'added to balance' : tone === 'debit' ? 'reduced / outstanding' : 'saved locally'}</small></article>; }
function SetupRequired() { return <section className="feature-placeholder"><span className="placeholder-icon"><AppIcon name="building" aria-hidden="true" size={28} /></span><p className="eyebrow">COMPANY LEDGER</p><h1>Set up your workspace first.</h1><p>Your company balance uses the private salary workspace configured during onboarding.</p><Link className="primary-button" href="/onboarding">Start setup <AppIcon name="arrow-right" aria-hidden="true" size={17} /></Link></section>; }
