'use client';

import { useEffect } from 'react';
import type { AppLanguage } from '@/types/domain';

const urdu: Record<string, string> = {
  // Navigation & Shell
  'PRIVATE FINANCE WORKSPACE': 'نجی مالی ورک اسپیس',
  'LIVE SALARY TICKER': 'لائیو سیلری ٹِکر',
  'ATTENDANCE': 'حاضری',
  'COMPANY LEDGER': 'کمپنی لیجر',
  'PERSONAL POCKET': 'ذاتی رقم',
  'CAREER HISTORY': 'کیریئر کی تاریخ',
  'LOCAL REPORTS': 'مقامی رپورٹس',
  'SETTINGS': 'ترتیبات',
  'LOAN TRACKER': 'قرض ٹریکر',
  'NEW ENTRY': 'نیا اندراج',
  'NEW POCKET ENTRY': 'ذاتی رقم کا نیا اندراج',
  'POCKET LEDGER': 'ذاتی لیجر',
  'SAVINGS GOALS': 'سیونگ گولز',
  'SAVINGS TRANSFER': 'سیونگ ٹرانسفر',
  'UDHAAR REMINDERS': 'ادھار یاد دہانیاں',
  'CURRENT ROLE': 'موجودہ عہدہ',
  'PAST EMPLOYMENT': 'گزشتہ ملازمت',
  'NET LIVE EARNINGS': 'خالص لائیو آمدنی',
  'CURRENT COMPANY BALANCE': 'موجودہ کمپنی بیلنس',
  'AVAILABLE CASH': 'دستیاب نقد رقم',
  'ESTIMATED LIFETIME EARNINGS': 'تخمینی زندگی بھر کی آمدنی',
  'PROFILE': 'پروفائل',
  'SALARY': 'تنخواہ',
  'SECURITY': 'سکیورٹی',
  'BACKUP': 'بیک اپ',
  'DISPLAY': 'ڈسپلے',
  'LOCAL APP LOCK': 'مقامی ایپ لاک',
  'EXPORT BACKUP': 'بیک اپ ایکسپورٹ کریں',
  'RESTORE BACKUP': 'بیک اپ بحال کریں',
  'RESTORE PREVIEW': 'بحالی کا جائزہ',
  'ADD A PAST ROLE': 'گزشتہ عہدہ شامل کریں',
  'LEDGER': 'لیجر',
  'MONTH VIEW': 'ماہانہ منظر',
  'ATTENDANCE EDITOR': 'حاضری ایڈیٹر',
  'NEW TARGET': 'نیا ہدف',
  'FIRST TIME HERE?': 'پہلی بار آئے ہیں؟',
  'GET STARTED': 'شروع کریں',
  'LIVE NOW': 'ابھی لائیو',
  'ONBOARDING': 'آن بورڈنگ',
  'SPREADSHEET READY': 'اسپریڈشیٹ کے لیے تیار',
  'PRINTABLE SUMMARY': 'پرنٹ ایبل خلاصہ',
  'VOUCHER IMAGE': 'واؤچر تصویر',
  'INCLUDED IN PDF': 'PDF میں شامل',

  // Headings & Subtitles
  'Your time, on record.': 'آپ کا وقت، ریکارڈ پر۔',
  'Mark each day your way. Automatic defaults never replace what you record yourself.': 'ہر دن کو اپنی مرضی سے درج کریں۔ خودکار ڈیفالٹس آپ کے دستی ریکارڈ کو تبدیل نہیں کرتے۔',
  'Know what’s outstanding.': 'جانیں کتنا باقی ہے۔',
  'Log company movements and track each loan repayment locally. Totals always come from the full record.': 'کمپنی کی نقل و حرکت درج کریں اور ہر قرض کی واپسی مقامی طور پر دیکھیں۔ کل ہمیشہ مکمل ریکارڈ سے آتے ہیں۔',
  'Keep your personal money clear.': 'اپنی ذاتی رقم کا حساب صاف رکھیں۔',
  'Cash, receipts, transfers, Udhaar, and savings stay on this device and never change your company balance.': 'نقد رقم، رسیدیں، ٹرانسفر، ادھار اور بچت اسی ڈیوائس پر رہتے ہیں اور کمپنی بیلنس کو تبدیل نہیں کرتے۔',
  'See the long view of your work.': 'اپنے کام کی طویل تصویر دیکھیں۔',
  'Past roles are archived here, separately from today’s live salary and personal pocket.': 'گزشتہ عہدے یہاں محفوظ رہتے ہیں، آج کی تنخواہ اور ذاتی رقم سے الگ۔',
  'Take your records with you.': 'اپنے ریکارڈ ساتھ لے جائیں۔',
  'Exports are prepared in your browser from this device’s records. Nothing is sent to a server.': 'ایکسپورٹس اسی ڈیوائس کے ریکارڈ سے آپ کے براؤزر میں بنتی ہیں۔ کچھ سرور پر نہیں جاتا۔',
  'Rules you control.': 'اصول جو آپ کے کنٹرول میں ہیں۔',
  'Update your profile and salary rules. Changes remain on this device.': 'اپنا پروفائل اور تنخواہ کے اصول تبدیل کریں۔ تبدیلیاں اسی ڈیوائس پر رہیں گی۔',
  'Work identity': 'کام کی شناخت',
  'Earning rules': 'آمدنی کے اصول',
  'Shift defaults': 'شفٹ کے اصول',
  'Local app lock': 'مقامی ایپ لاک',
  'Encrypted backup and restore': 'خفیہ بیک اپ اور بحالی',
  'Preferences': 'ترجیحات',
  'Your workspace is locked.': 'آپ کا ورک اسپیس لاک ہے۔',
  'Enter your PIN to view financial records stored on this device.': 'اس ڈیوائس پر محفوظ مالی ریکارڈ دیکھنے کے لیے اپنا پن درج کریں۔',
  'Your workspace checklist': 'آپ کی ورک اسپیس فہرست',
  'Your private workspace is complete.': 'آپ کا نجی ورک اسپیس مکمل ہے۔',
  'Build your private salary wallet.': 'اپنا نجی سیلری والٹ بنائیں۔',
  'Good evening.': 'شام بخیر۔',
  'Good morning.': 'صبح بخیر۔',
  'Good afternoon.': 'دوپہر بخیر۔',
  'Your salary, attendance, and cash—always within reach.': 'آپ کی تنخواہ، حاضری اور کیش — ہمیشہ آپ کی پہنچ میں۔',
  'Set up your salary to begin': 'شروع کرنے کے لیے اپنی تنخواہ سیٹ اپ کریں',
  'Issue and settle company loans.': 'کمپنی کے قرضے جاری اور مکمل کریں۔',
  'Record another movement.': 'کمپنی کی ایک اور رقم درج کریں۔',
  'Move money without losing the trail.': 'ریکارڈ برقرار رکھتے ہوئے رقم منتقل کریں۔',
  'Give every saving a purpose.': 'ہر بچت کو ایک مقصد دیں۔',
  'Follow up on money lent.': 'دیے گئے ادھار کی یاد دہانی دیکھیں۔',
  'Keep your history complete.': 'اپنی کیریئر تاریخ مکمل رکھیں۔',
  'Clear, local, useful.': 'واضح، مقامی، مفید۔',
  'Make the workspace yours.': 'ورک اسپیس کو اپنا بنائیں۔',
  'Everything stays on this device. You can adjust every rule in Settings later.': 'سب کچھ اسی ڈیوائس پر رہتا ہے۔ آپ بعد میں ترتیبات میں ہر اصول تبدیل کر سکتے ہیں۔',
  'Who is this workspace for?': 'یہ ورک اسپیس کس کے لیے ہے؟',
  'Set your salary rules.': 'اپنی تنخواہ کے اصول طے کریں۔',
  'Finish your work style.': 'اپنا طریقۂ کار مکمل کریں۔',
  'Make an encrypted copy.': 'ایک خفیہ کاپی بنائیں۔',
  'Preview before replacing.': 'تبدیل کرنے سے پہلے جائزہ لیں۔',
  'You’re offline.': 'آپ آف لائن ہیں۔',

  // Form Fields & Labels
  'First name': 'پہلا نام',
  'Last name': 'آخری نام',
  'Employee ID': 'ملازم آئی ڈی',
  'Employee ID / roll number': 'ملازم آئی ڈی / رول نمبر',
  'Designation': 'عہدہ',
  'Joining date': 'شمولیت کی تاریخ',
  'Salary mode': 'تنخواہ کا طریقہ',
  'Base salary': 'بنیادی تنخواہ',
  'Base salary (PKR)': 'بنیادی تنخواہ (PKR)',
  'Base monthly salary (PKR)': 'بنیادی ماہانہ تنخواہ (PKR)',
  'Reference monthly salary (PKR)': 'حوالہ ماہانہ تنخواہ (PKR)',
  'Daily rate': 'یومیہ شرح',
  'Daily rate (PKR)': 'یومیہ شرح (PKR)',
  'Daily calculation rule': 'یومیہ حساب کا قاعدہ',
  'Duty starts': 'ڈیوٹی شروع',
  'Duty ends': 'ڈیوٹی ختم',
  'Shift duration (hours)': 'شفٹ کا دورانیہ (گھنٹے)',
  'Weekly off': 'ہفتہ وار چھٹی',
  'Auto-attendance': 'خودکار حاضری',
  'Custom attendance time': 'خودکار حاضری کا وقت',
  'Low-cash threshold (PKR)': 'کم رقم کی حد (PKR)',
  'Language': 'زبان',
  'Theme': 'تھیم',
  'Entry type': 'اندراج کی قسم',
  'Amount (PKR)': 'رقم (PKR)',
  'Date': 'تاریخ',
  'Note': 'نوٹ',
  'Category': 'زمرہ',
  'Status': 'حالت',
  'Check in': 'چیک اِن',
  'Check out': 'چیک آؤٹ',
  'Overtime (hours)': 'اوور ٹائم (گھنٹے)',
  'Loan name': 'قرض کا نام',
  'Principal (PKR)': 'اصل رقم (PKR)',
  'Issue date': 'اجرا کی تاریخ',
  'Repayment (PKR)': 'واپسی (PKR)',
  'Company': 'کمپنی',
  'Company name': 'کمپنی کا نام',
  'Your role': 'آپ کا عہدہ',
  'Start date': 'شروع کی تاریخ',
  'End date': 'اختتامی تاریخ',
  'Monthly salary (PKR)': 'ماہانہ تنخواہ (PKR)',
  'Company entry': 'کمپنی اندراج',
  'Direction': 'سمت',
  'Savings goal': 'سیونگ گول',
  'Reminder date': 'یاد دہانی کی تاریخ',
  'Goal name': 'گول کا نام',
  'Target (PKR)': 'ہدف رقم (PKR)',
  'Saved now (PKR)': 'اب تک بچت (PKR)',
  'Target date': 'ہدف کی تاریخ',
  'Backup passphrase': 'بیک اپ پاس فریز',
  'Confirm passphrase': 'پاس فریز کی تصدیق کریں',
  'Backup file': 'بیک اپ فائل',
  'Current PIN': 'موجودہ پن',
  'New PIN': 'نیا پن',
  'Choose a PIN': 'ایک پن منتخب کریں',
  'Confirm new PIN': 'نئے پن کی تصدیق کریں',
  'PIN': 'پن',
  'Required': 'لازمی',
  'optional': 'اختیاری',

  // Select Options & Dropdown Values
  'Fixed monthly': 'مقررہ ماہانہ',
  '30-days': '30 دن کا قاعدہ',
  '30-day rule': '30 دن کا قاعدہ',
  '26-working-days': '26 کام کے دنوں کا قاعدہ',
  '26-working-day rule': '26 کام کے دنوں کا قاعدہ',
  'calendar-days': 'کیلنڈر کے دنوں کا قاعدہ',
  'Calendar-day rule': 'کیلنڈر کے دنوں کا قاعدہ',
  'Off — manual only': 'بند — صرف دستی',
  'At midnight': 'آدھی رات کو',
  'At shift end': 'شفٹ کے اختتام پر',
  'At a custom time': 'مخصوص وقت پر',
  'Sunday': 'اتوار',
  'Monday': 'پیر',
  'Tuesday': 'منگل',
  'Wednesday': 'بدھ',
  'Thursday': 'جمعرات',
  'Friday': 'جمعہ',
  'Saturday': 'ہفتہ',
  'Sun': 'اتوار',
  'Mon': 'پیر',
  'Tue': 'منگل',
  'Wed': 'بدھ',
  'Thu': 'جمعرات',
  'Fri': 'جمعہ',
  'Sat': 'ہفتہ',
  'English': 'انگریزی',
  'Urdu': 'اردو',
  'Dark neon': 'گہرا نیون',
  'Light': 'روشن',
  'Show saved status': 'محفوظ شدہ حالت دکھائیں',
  'All recorded statuses': 'تمام ریکارڈ شدہ حالات',
  'Present': 'حاضر',
  'Absent': 'غیر حاضر',
  'Half day': 'آدھا دن',
  'Leave': 'چھٹی',
  'Away': 'غیر حاضر',
  'Cash in': 'رقم وصول',
  'Expense': 'خرچ',
  'Receipt': 'رسید',
  'Udhaar given': 'ادھار دیا',
  'Udhaar received': 'ادھار وصول',
  'To savings': 'سیونگ میں',
  'From savings': 'سیونگ سے',
  'Company credit': 'کمپنی کریڈٹ',
  'Withdrawal': 'رقم نکلوائی',
  'Voucher': 'واؤچر',
  'Advance': 'ایڈوانس',
  'Loan issued': 'قرض جاری',
  'Loan repayment': 'قرض کی واپسی',
  'Deduction': 'کٹوتی',
  'Income': 'آمدن',
  'Food': 'کھانا',
  'Transport': 'ٹرانسپورٹ',
  'Bills': 'بلز',
  'Shopping': 'خریداری',
  'Health': 'صحت',
  'Education': 'تعلیم',
  'Family': 'خاندان',
  'Entertainment': 'تفریح',
  'Other': 'دیگر',
  'Pocket cash → savings goal': 'ذاتی رقم ← سیونگ گول',
  'Savings goal → pocket cash': 'سیونگ گول ← ذاتی رقم',
  'Choose a goal': 'گول منتخب کریں',
  'Most recent entry': 'سب سے حالیہ اندراج',
  'No company entries yet': 'ابھی کوئی کمپنی اندراج نہیں',

  // Buttons & Actions
  'Save changes': 'تبدیلیاں محفوظ کریں',
  'Saving…': 'محفوظ ہو رہا ہے…',
  'Add entry': 'اندراج شامل کریں',
  'Issue loan': 'قرض جاری کریں',
  'Record repayment': 'واپسی درج کریں',
  'Save day': 'دن محفوظ کریں',
  'Save role': 'عہدہ محفوظ کریں',
  'Create goal': 'گول بنائیں',
  'Update': 'تبدیل کریں',
  'Save transfer': 'ٹرانسفر محفوظ کریں',
  'Download CSV': 'CSV ڈاؤن لوڈ کریں',
  'Download PDF': 'PDF ڈاؤن لوڈ کریں',
  'Download voucher': 'واؤچر ڈاؤن لوڈ کریں',
  'Open reports': 'رپورٹس کھولیں',
  'Start setup': 'سیٹ اپ شروع کریں',
  'Adjust': 'تبدیل کریں',
  'Clear reminder': 'یاد دہانی صاف کریں',
  'Clearing…': 'صاف ہو رہا ہے…',
  'Remove': 'حذف کریں',
  'Close': 'بند کریں',
  'Set up now': 'ابھی سیٹ اپ کریں',
  'Lock now': 'ابھی لاک کریں',
  'Update PIN': 'پن تبدیل کریں',
  'Enable PIN lock': 'پن لاک فعال کریں',
  'Remove PIN lock': 'پن لاک ختم کریں',
  'Add passkey': 'پاس کی شامل کریں',
  'Remove passkey': 'پاس کی ہٹائیں',
  'Download encrypted backup': 'خفیہ بیک اپ ڈاؤن لوڈ کریں',
  'Decrypt and preview': 'ڈیکرپٹ کر کے جائزہ لیں',
  'Replace local data with this backup': 'مقامی ڈیٹا کو اس بیک اپ سے تبدیل کریں',
  'Type ': 'لکھیں ',
  ' to enable this irreversible action.': ' اس ناقابل واپسی عمل کو فعال کرنے کے لیے۔',
  'Restoring…': 'بحالی جاری ہے…',
  'Preparing…': 'تیاری جاری ہے…',
  'Checking…': 'چیک ہو رہا ہے…',
  'Unlock workspace': 'ورک اسپیس کھولیں',
  'Use this device’s passkey': 'اس ڈیوائس کی پاس کی استعمال کریں',
  'Use this device\'s passkey': 'اس ڈیوائس کی پاس کی استعمال کریں',
  'Today': 'آج',
  'Clear filter': 'فلٹر صاف کریں',
  'Next unrecorded workday': 'اگلا غیر ریکارڈ شدہ دن',
  'Fill unrecorded days': 'غیر ریکارڈ شدہ دن پر کریں',
  'Attach receipt': 'رسید منسلک کریں',
  'Replace receipt': 'رسید تبدیل کریں',
  'Remove receipt': 'رسید ہٹائیں',
  'Back': 'پیچھے',
  'Continue': 'آگے بڑھیں',
  'Finish setup': 'سیٹ اپ مکمل کریں',

  // Switches & Descriptions
  'Weekly off is paid': 'ہفتہ وار چھٹی با معاوضہ ہے',
  'Counts the selected weekly off as a full paid day.': 'منتخب کردہ ہفتہ وار چھٹی کو مکمل با معاوضہ دن شمار کرتا ہے۔',
  'Counts the configured weekly off as a full paid day.': 'ہفتہ وار چھٹی کو مکمل با معاوضہ دن شمار کرتا ہے۔',
  'Privacy mode at startup': 'شروع میں رازداری موڈ',
  'Blurs financial figures until you reveal them.': 'مالی رقوم کو دکھانے تک دھندلا رکھیں۔',
  'Keep financial figures hidden until you reveal them.': 'مالی رقوم کو چھپا کر رکھیں جب تک آپ انہیں ظاہر نہ کریں۔',

  // Badges, Cards & Counters
  'Credits': 'کریڈٹس',
  'Deductions': 'کٹوتیاں',
  'Loans due': 'واجب الادا قرضے',
  'Entries': 'اندراجات',
  'Money in': 'آمدن',
  'Money out': 'خرچ',
  'Saved toward goals': 'گولز کے لیے بچت',
  'Recent activity': 'حالیہ سرگرمی',
  'Your history': 'آپ کی تاریخ',
  'Recorded': 'ریکارڈ شدہ',
  'Time off': 'چھٹی کا وقت',
  'Overtime': 'اوور ٹائم',
  'days this month': 'اس ماہ کے دن',
  'full days': 'مکمل دن',
  'absent or leave': 'غیر حاضر یا رخصت',
  'recorded': 'ریکارڈ شدہ',
  'records this month': 'اس ماہ کے ریکارڈز',
  'Settled': 'مکمل',
  'Open': 'جاری',
  'Outstanding': 'بقایا',
  'Repaid': 'واپس شدہ',
  'repaid of': 'واپس شدہ از',
  'scheduled': 'طے شدہ',
  'Due': 'واجب الادا',
  'Due on': 'آخری تاریخ',
  'goals': 'گولز',
  'roles': 'عہدے',
  'total': 'کل',
  'open': 'جاری',
  'estimated earned': 'تخمینی کمائی',
  'Local live rate': 'مقامی لائیو شرح',
  'Local only': 'صرف مقامی',
  'Private & local': 'نجی اور مقامی',
  'Available credit': 'دستیاب کریڈٹ',
  'Per month': 'فی ماہ',
  'Per day': 'فی دن',
  'from local records': 'مقامی ریکارڈز سے',
  'Saved records': 'محفوظ شدہ ریکارڈز',
  'Profiles': 'پروفائلز',
  'Company entries': 'کمپنی اندراجات',
  'Company loans': 'کمپنی قرضے',
  'Pocket entries': 'ذاتی رقم اندراجات',
  'Savings goals': 'سیونگ گولز',
  'Career records': 'کیریئر ریکارڈز',

  // Empty States & Hints
  'No company entries yet.': 'ابھی کوئی کمپنی اندراج نہیں۔',
  'No tracked loans yet.': 'ابھی کوئی ٹریک شدہ قرض نہیں۔',
  'No pocket entries yet.': 'ابھی کوئی ذاتی رقم کا اندراج نہیں۔',
  'No savings goals yet.': 'ابھی کوئی سیونگ گول نہیں۔',
  'No past roles added yet.': 'ابھی کوئی گزشتہ عہدہ شامل نہیں۔',
  'Set up your workspace first.': 'پہلے اپنا ورک اسپیس سیٹ اپ کریں۔',
  'Loading local settings…': 'مقامی ترتیبات لوڈ ہو رہی ہیں…',
  'Checking local security…': 'مقامی سکیورٹی چیک ہو رہی ہے…',
  'PIN lock is on': 'پن لاک فعال ہے',
  'PIN lock is off': 'پن لاک غیر فعال ہے',
  'Financial views lock again when this browser session ends.': 'براؤزر سیشن ختم ہونے پر مالی اسکرینیں دوبارہ لاک ہو جائیں گی۔',
  'Set a PIN to require an unlock when opening the workspace.': 'ورک اسپیس کھولتے وقت لاک کھولنے کے لیے پن مقرر کریں۔',
  'Use 4–8 digits. The app saves only a PBKDF2 hash and random salt, never the PIN itself.': '4 سے 8 ہندسے استعمال کریں۔ ایپ صرف خفیہ ہیش اور سالٹ محفوظ کرتی ہے، پن نہیں۔',
  'Local passkey shortcut': 'مقامی پاس کی شارٹ کٹ',
  'Available on this browser or device.': 'اس براؤزر یا ڈیوائس پر دستیاب ہے۔',
  'Optional. Compatible secure browsers can use their built-in device check.': 'اختیاری۔ مطابقت رکھنے والے محفوظ براؤزرز اپنے اندرونی ڈیوائس چیک کا استعمال کر سکتے ہیں۔',
  'Passkeys are a local convenience check in this offline app. They are not backed by an external server, and they are not included in backups.': 'پاس کیز اس آف لائن ایپ میں سہولت کے لیے ہیں۔ وہ کسی بیرونی سرور پر نہیں اور بیک اپ میں شامل نہیں ہوتیں۔',
  'All local finance and career records are encrypted in a portable .lstbackup file.': 'تمام مقامی مالی اور کیریئر ریکارڈز .lstbackup فائل میں خفیہ محفوظ کیے جاتے ہیں۔',
  'Only a decrypted, validated backup can replace the local finance records on this device.': 'صرف درست اور تصدیق شدہ بیک اپ ہی اس ڈیوائس پر موجود ڈیٹا کی جگہ لے سکتا ہے۔',
  'I understand that restoring will replace the current local finance records.': 'میں سمجھتا ہوں کہ بحال کرنے سے موجودہ مقامی مالی ریکارڈ تبدیل ہو جائے گا۔',
  'PIN verification happens locally. No financial data is sent anywhere.': 'پن کی تصدیق مقامی طور پر ہوتی ہے۔ کوئی مالی ڈیٹا کہیں نہیں بھیجا جاتا۔',
  'Use your work identity—not a public username.': 'اپنی دفتری شناخت استعمال کریں — عوامی نام نہیں۔',
  'Fixed monthly salary stays constant regardless of the calendar month length.': 'مقررہ ماہانہ تنخواہ کیلنڈر کے دنوں سے قطع نظر یکساں رہتی ہے۔',
  'Default: monthly salary ÷ 30. You can revise this rule later without altering historical records.': 'ڈیفالٹ: ماہانہ تنخواہ ÷ 30۔ آپ ماضی کے ریکارڈ کو بدلے بغیر بعد میں اسے تبدیل کر سکتے ہیں۔',
  'Automatic attendance runs while this workspace is open or when you return to it. It only fills blank workdays and never overwrites manual entries.': 'خودکار حاضری ایپ کھلی ہونے یا واپس آنے پر چلتی ہے۔ یہ صرف خالی دن پر کرتی ہے اور دستی اندراجات کو تبدیل نہیں کرتی۔',
  'Automatic attendance checks while this workspace is open or when you return to it. It only fills a blank eligible day and never changes manual entries.': 'خودکار حاضری ایپ کھلی ہونے یا واپس آنے پر چیک ہوتی ہے۔ یہ صرف خالی دن پر کرتی ہے اور دستی اندراجات کو تبدیل نہیں کرتی۔',
  'Issuing a loan creates a linked debit in the company ledger. Repayments can never exceed the remaining principal.': 'قرض جاری کرنے سے لیجر میں کٹوتی شامل ہوتی ہے۔ واپسی کبھی بقایا اصل رقم سے زیادہ نہیں ہو سکتی۔',
  'Use the loan tracker above for loans and repayments. Credits increase balance; these other entries reduce it.': 'قرضوں اور واپسیوں کے لیے اوپر دیا گیا قرض ٹریکر استعمال کریں۔ کریڈٹ بیلنس بڑھاتے ہیں؛ باقی اندراجات اسے کم کرتے ہیں۔',
  'Categories, receipt images, and Udhaar reminders remain only on this device.': 'زمرہ جات، رسیدوں کی تصاویر اور ادھار یاد دہانیاں صرف اسی ڈیوائس پر رہتی ہیں۔',
  'Create a savings goal first. Transfers then create a linked pocket ledger entry and update that goal automatically.': 'پہلے سیونگ گول بنائیں۔ پھر ٹرانسفرز خودکار طور پر لیجر اور گول کو اپ ڈیٹ کر دیں گے۔',
  'Add completed employment only. Your active role is calculated from your salary setup.': 'صرف مکمل شدہ ملازمت شامل کریں۔ فعال عہدے کا حساب تنخواہ کے سیٹ اپ سے ہوتا ہے۔',
  'Historical roles plus your current role so far. Past-role totals use a simple 30-day monthly pro-rate.': 'گزشتہ عہدے مع موجودہ ملازمت۔ گزشتہ عہدوں کے کل کے لیے 30 دن کا ماہانہ حساب لاگو ہوتا ہے۔',
  'Current company and personal balances': 'موجودہ کمپنی اور ذاتی بیلنس',
  'Attendance, career, and savings counts': 'حاضری، کیریئر اور بچت کی تعداد',
  'Five most recent company and pocket entries': 'کمپنی اور ذاتی رقم کے پانچ حالیہ اندراجات',
  'Up to four savings-goal progress summaries': 'چار تک سیونگ گولز کی پیشرفت کا خلاصہ',
  'Only blank workdays through today are marked present. Existing entries stay untouched.': 'صرف آج تک کے خالی کام کے دنوں کو حاضر لگایا جاتا ہے۔ پہلے سے موجود اندراجات محفوظ رہتے ہیں۔',
  'Fill past scheduled workdays': 'گزشتہ کام کے دن درج کریں',
  'Personal money recorded locally': 'مقامی طور پر ریکارڈ شدہ ذاتی رقم',
  'Outgoing entries exceed incoming money': 'اخراجات وصول شدہ رقم سے زیادہ ہیں',
  'Receipt image': 'رسید کی تصویر',
  'Optional JPG, PNG, or WebP · max 1 MB': 'اختیاری JPG, PNG یا WebP · زیادہ سے زیادہ 1 MB',
  'Selected receipt preview': 'منتخب رسید کا پریویو',

  // Placeholders
  'Optional detail': 'اختیاری تفصیل',
  'Optional explanation': 'اختیاری وضاحت',
  'Optional repayment note': 'اختیاری واپسی نوٹ',
  'Optional reference or explanation': 'اختیاری حوالہ یا وضاحت',
  'Optional achievement or detail': 'اختیاری کارنامہ یا تفصیل',
  'Optional reminder': 'اختیاری یاد دہانی',
  'At least 8 characters': 'کم از کم 8 حروف',
  'Repeat passphrase': 'پاس فریز دہرائیں',
  'Passphrase used for export': 'ایکسپورٹ کا پاس فریز',
  'e.g. Laptop advance': 'مثلاً لیپ ٹاپ ایڈوانس',
  'Emergency fund': 'ہنگامی فنڈ',
  'Muhammad': 'محمد',
  'Naeem': 'نعیم',
  'Junior Accountant': 'اکاؤنٹنٹ',
  '1042': '1042',
};

const originalText = new WeakMap<Text, string>();
const originalAttributes = new WeakMap<Element, Map<string, string>>();
const translatableAttributes = ['aria-label', 'placeholder', 'title'] as const;

export function LocalizedSurface({ language }: { language: AppLanguage | undefined }) {
  useEffect(() => {
    const root = document.querySelector<HTMLElement>('[data-localized-surface]');
    if (!root) return;
    const translate = (value: string) => language === 'ur' ? urdu[value] ?? value : value;
    const updateText = (node: Text) => {
      const parent = node.parentElement;
      if (!parent || parent.closest('[data-user-content]') || ['SCRIPT', 'STYLE'].includes(parent.tagName)) return;
      const source = originalText.get(node) ?? node.nodeValue ?? '';
      originalText.set(node, source);
      const next = translate(source);
      if (node.nodeValue !== next) node.nodeValue = next;
    };
    const updateElement = (element: Element) => {
      if (element.closest('[data-user-content]')) return;
      translatableAttributes.forEach((attribute) => {
        const value = element.getAttribute(attribute);
        if (value === null) return;
        const originals = originalAttributes.get(element) ?? new Map<string, string>();
        if (!originalAttributes.has(element)) originalAttributes.set(element, originals);
        const source = originals.get(attribute) ?? value;
        originals.set(attribute, source);
        const next = translate(source);
        if (value !== next) element.setAttribute(attribute, next);
      });
    };
    const updateTree = (node: Node) => {
      if (node.nodeType === Node.TEXT_NODE) updateText(node as Text);
      if (node.nodeType !== Node.ELEMENT_NODE) return;
      const element = node as Element;
      updateElement(element);
      element.querySelectorAll('*').forEach(updateElement);
      const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
      let current: Node | null = walker.nextNode();
      while (current) { updateText(current as Text); current = walker.nextNode(); }
    };
    updateTree(root);
    const observer = new MutationObserver((records) => records.forEach((record) => {
      if (record.type === 'characterData') updateText(record.target as Text);
      record.addedNodes.forEach(updateTree);
    }));
    observer.observe(root, { childList: true, subtree: true, characterData: true });
    return () => observer.disconnect();
  }, [language]);

  return null;
}
