'use client';

/* eslint-disable @next/next/no-img-element -- Receipt images are local data URLs and must not be sent to an image optimizer. */

import Link from 'next/link';
import { useState, type ChangeEvent, type FormEvent } from 'react';
import { AppIcon } from '@/components/ui/app-icon';
import { getPocketBalance, isPocketDebit } from '@/lib/calculations/pocket-balance';
import { addPocketTransaction, addSavingsGoal, addSavingsTransfer, clearUdhaarReminder, deletePocketTransaction, deleteSavingsGoal, updateSavingsGoal } from '@/lib/database/repository';
import { formatCurrency } from '@/lib/formatting/currency';
import { formatDate, getLocalDateValue } from '@/lib/formatting/date';
import { MAX_RECEIPT_DATA_URL_LENGTH, pocketCategories } from '@/lib/validation/domain';
import { useCurrentAppRecords } from '@/hooks/use-current-app-records';
import { usePocketRecords } from '@/hooks/use-pocket-records';
import { useAppTranslation } from '@/hooks/use-app-translation';
import type { PocketCategory, PocketTransaction, PocketTransactionType, SavingsGoal } from '@/types/domain';

const transactionLabels: Record<PocketTransactionType, string> = { 'cash-in': 'Cash in', expense: 'Expense', receipt: 'Receipt', 'udhaar-given': 'Udhaar given', 'udhaar-received': 'Udhaar received', 'savings-transfer-out': 'To savings', 'savings-transfer-in': 'From savings' };
const categoryLabels: Record<PocketCategory, string> = { income: 'Income', food: 'Food', transport: 'Transport', bills: 'Bills', shopping: 'Shopping', health: 'Health', education: 'Education', family: 'Family', entertainment: 'Entertainment', other: 'Other' };
const entryTypes: PocketTransactionType[] = ['cash-in', 'expense', 'receipt', 'udhaar-given', 'udhaar-received'];
const maxReceiptBytes = 1_000_000;

export function PocketContent() {
  const { t } = useAppTranslation();
  const { records, isLoading, isOnboarded } = useCurrentAppRecords();
  const { transactions, goals, isLoading: recordsLoading } = usePocketRecords();
  if (isLoading || recordsLoading) return <section className="dashboard-loading" aria-live="polite">Loading your private pocket…</section>;
  if (!isOnboarded) return <SetupRequired />;
  const balance = getPocketBalance(transactions);
  const incoming = transactions.filter((transaction) => !isPocketDebit(transaction.type)).reduce((total, transaction) => total + transaction.amount, 0);
  const outgoing = transactions.filter((transaction) => isPocketDebit(transaction.type)).reduce((total, transaction) => total + transaction.amount, 0);
  const saved = goals.reduce((total, goal) => total + goal.savedAmount, 0);
  const threshold = records?.appSettings?.lowCashThreshold ?? 0;
  const reminders = transactions.filter((transaction) => transaction.type === 'udhaar-given' && transaction.reminderOn).sort((first, second) => (first.reminderOn ?? '').localeCompare(second.reminderOn ?? ''));
  return <section className="pocket-page">
    <header className="page-heading"><div><p className="eyebrow">PERSONAL POCKET</p><h1>Keep your personal money clear.</h1><p className="page-subtitle">Cash, receipts, transfers, Udhaar, and savings stay on this device and never change your company balance.</p></div></header>
    <section className="pocket-balance-card"><div><p className="eyebrow">AVAILABLE CASH</p><strong className={balance < 0 ? 'balance-negative' : ''}>{formatCurrency(balance)}</strong><p>{balance >= 0 ? 'Personal money recorded locally' : 'Outgoing entries exceed incoming money'}</p></div><span className="local-pill"><span className="pulse-dot" />Private &amp; local</span></section>
    {threshold > 0 && balance <= threshold ? <section className="pocket-alert" role="status"><AppIcon name="wallet" aria-hidden="true" size={20} /><div><strong>{t('lowCashAlert')}</strong><span>{formatCurrency(balance)} is at or below your {formatCurrency(threshold)} threshold.</span></div><Link href="/settings" className="secondary-button">{t('adjust')}</Link></section> : null}
    <div className="company-summary pocket-summary"><SummaryCard label="Money in" amount={incoming} tone="credit" /><SummaryCard label="Money out" amount={outgoing} tone="debit" /><SummaryCard label="Saved toward goals" amount={saved} tone="neutral" /></div>
    {reminders.length ? <UdhaarReminderPanel reminders={reminders} /> : null}
    <div className="pocket-layout"><TransactionForm /><TransactionList transactions={transactions} goals={goals} /></div>
    <section className="transfer-section"><div className="panel-heading"><div><p className="eyebrow">SAVINGS TRANSFER</p><h2>Move money without losing the trail.</h2></div></div><SavingsTransferForm goals={goals} /></section>
    <section className="savings-section"><div className="panel-heading"><div><p className="eyebrow">SAVINGS GOALS</p><h2>Give every saving a purpose.</h2></div><span className="progress-label">{goals.length} goals</span></div><div className="savings-layout"><SavingsGoalForm /><div className="savings-goal-list">{goals.length ? goals.map((goal) => <SavingsGoalCard key={goal.id} goal={goal} />) : <div className="ledger-empty"><AppIcon name="wallet" aria-hidden="true" size={24} /><p>No savings goals yet.</p><span>Create a target before moving pocket cash into it.</span></div>}</div></div></section>
  </section>;
}

function TransactionForm() {
  const [type, setType] = useState<PocketTransactionType>('cash-in'); const [amount, setAmount] = useState(''); const [occurredOn, setOccurredOn] = useState(getLocalDateValue); const [category, setCategory] = useState<PocketCategory>('other'); const [note, setNote] = useState(''); const [reminderOn, setReminderOn] = useState(''); const [receiptDataUrl, setReceiptDataUrl] = useState<string | null>(null); const [status, setStatus] = useState(''); const [isSaving, setIsSaving] = useState(false);
  const selectReceipt = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > maxReceiptBytes) { setStatus('Choose a JPG, PNG, or WebP receipt no larger than 1 MB.'); return; } try { const dataUrl = await readReceipt(file); if (dataUrl.length > MAX_RECEIPT_DATA_URL_LENGTH) throw new Error(); setReceiptDataUrl(dataUrl); setStatus('Receipt image is ready and will stay on this device.'); } catch { setStatus('Could not read that receipt image.'); } };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const parsedAmount = Number(amount); if (!Number.isFinite(parsedAmount) || parsedAmount <= 0) { setStatus('Enter an amount greater than zero.'); return; } setIsSaving(true); setStatus(''); try { await addPocketTransaction({ type, amount: parsedAmount, occurredOn, category, note: note.trim(), receiptDataUrl, savingsGoalId: null, reminderOn: type === 'udhaar-given' ? reminderOn || null : null }); setAmount(''); setNote(''); setCategory('other'); setReminderOn(''); setReceiptDataUrl(null); setStatus('Pocket entry saved locally.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Could not save this pocket entry.'); } finally { setIsSaving(false); } };
  return <section className="company-entry-form"><div><p className="eyebrow">NEW POCKET ENTRY</p><h2>Record a movement.</h2><p>Categories, receipt images, and Udhaar reminders remain only on this device.</p></div><form onSubmit={submit}><label className="field"><span>Entry type</span><select value={type} onChange={(event) => setType(event.target.value as PocketTransactionType)}>{entryTypes.map((value) => <option value={value} key={value}>{transactionLabels[value]}</option>)}</select></label><div className="form-grid compact-form-grid"><label className="field"><span>Amount (PKR)</span><input type="number" min="1" inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0" required /></label><label className="field"><span>Date</span><input type="date" value={occurredOn} onChange={(event) => setOccurredOn(event.target.value)} required /></label></div><label className="field"><span>Category</span><select value={category} onChange={(event) => setCategory(event.target.value as PocketCategory)}>{pocketCategories.map((value) => <option value={value} key={value}>{categoryLabels[value]}</option>)}</select></label>{type === 'udhaar-given' ? <label className="field"><span>Reminder date <em>optional</em></span><input type="date" value={reminderOn} onChange={(event) => setReminderOn(event.target.value)} /></label> : null}<label className="field"><span>Note</span><input maxLength={140} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional detail" /></label><div className="receipt-picker"><div><strong>Receipt image</strong><small>Optional JPG, PNG, or WebP · max 1 MB</small></div><label className="secondary-button"><span>{receiptDataUrl ? 'Replace receipt' : 'Attach receipt'}</span><input accept="image/jpeg,image/png,image/webp" type="file" onChange={selectReceipt} /></label>{receiptDataUrl ? <><img src={receiptDataUrl} alt="Selected receipt preview" /><button className="remove-button" type="button" onClick={() => { setReceiptDataUrl(null); setStatus('Receipt removed before saving.'); }}>Remove receipt</button></> : null}</div><div className="editor-actions"><span role="status">{status}</span><button className="primary-button" type="submit" disabled={isSaving}>{isSaving ? 'Saving…' : 'Add entry'} <AppIcon name="plus" aria-hidden="true" size={17} /></button></div></form></section>;
}

function SavingsTransferForm({ goals }: { goals: SavingsGoal[] }) { const { t } = useAppTranslation(); const [direction, setDirection] = useState<'to-goal' | 'from-goal'>('to-goal'); const [goalId, setGoalId] = useState(''); const [amount, setAmount] = useState(''); const [occurredOn, setOccurredOn] = useState(getLocalDateValue); const [note, setNote] = useState(''); const [status, setStatus] = useState(''); const [isSaving, setIsSaving] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const value = Number(amount); if (!goalId || !Number.isFinite(value) || value <= 0) { setStatus('Choose a goal and enter an amount greater than zero.'); return; } setIsSaving(true); setStatus(''); try { await addSavingsTransfer({ direction, savingsGoalId: goalId, amount: value, occurredOn, note: note.trim() }); setAmount(''); setNote(''); setStatus(t('transferSaved')); } catch (error) { setStatus(error instanceof Error ? error.message : 'Could not save this transfer.'); } finally { setIsSaving(false); } }; if (!goals.length) return <p className="form-hint">Create a savings goal first. Transfers then create a linked pocket ledger entry and update that goal automatically.</p>; return <form className="transfer-form" onSubmit={submit}><label className="field"><span>Direction</span><select value={direction} onChange={(event) => setDirection(event.target.value as 'to-goal' | 'from-goal')}><option value="to-goal">Pocket cash → savings goal</option><option value="from-goal">Savings goal → pocket cash</option></select></label><label className="field"><span>Savings goal</span><select value={goalId} onChange={(event) => setGoalId(event.target.value)} required><option value="">Choose a goal</option>{goals.map((goal) => <option value={goal.id} key={goal.id}>{goal.name} · {formatCurrency(goal.savedAmount)}</option>)}</select></label><div className="form-grid compact-form-grid"><label className="field"><span>Amount (PKR)</span><input type="number" min="1" value={amount} onChange={(event) => setAmount(event.target.value)} required /></label><label className="field"><span>Date</span><input type="date" value={occurredOn} onChange={(event) => setOccurredOn(event.target.value)} required /></label></div><label className="field"><span>Note</span><input maxLength={140} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional detail" /></label><div className="editor-actions"><span role="status">{status}</span><button className="secondary-button" type="submit" disabled={isSaving}>{isSaving ? t('saving') : t('saveTransfer')}</button></div></form>; }

function UdhaarReminderPanel({ reminders }: { reminders: PocketTransaction[] }) { const [clearingId, setClearingId] = useState<string | null>(null); const [status, setStatus] = useState(''); const today = getLocalDateValue(); const clear = async (id: string) => { setClearingId(id); setStatus(''); try { await clearUdhaarReminder(id); setStatus('Reminder cleared; the Udhaar ledger entry remains saved.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Could not clear this reminder.'); } finally { setClearingId(null); } }; return <section className="udhaar-reminders"><div className="panel-heading"><div><p className="eyebrow">UDHAAR REMINDERS</p><h2>Follow up on money lent.</h2></div><span className="progress-label">{reminders.length} scheduled</span></div><ul>{reminders.map((transaction) => <li key={transaction.id}><div><strong>{transaction.note || 'Udhaar given'}</strong><small className={transaction.reminderOn! <= today ? 'reminder-overdue' : ''}>{transaction.reminderOn! <= today ? 'Due' : 'Due on'} {formatDate(transaction.reminderOn!)}</small></div><b>{formatCurrency(transaction.amount)}</b><button type="button" className="secondary-button" disabled={clearingId === transaction.id} onClick={() => clear(transaction.id)}>{clearingId === transaction.id ? 'Clearing…' : 'Clear reminder'}</button></li>)}</ul><span className="field-status" role="status">{status}</span></section>; }

function TransactionList({ transactions, goals }: { transactions: PocketTransaction[]; goals: SavingsGoal[] }) { const [removingId, setRemovingId] = useState<string | null>(null); const [viewingReceipt, setViewingReceipt] = useState<PocketTransaction | null>(null); const goalNames = new Map(goals.map((goal) => [goal.id, goal.name])); const remove = async (transaction: PocketTransaction) => { if (!window.confirm(`Remove ${transactionLabels[transaction.type].toLowerCase()} from ${formatDate(transaction.occurredOn)}?`)) return; setRemovingId(transaction.id); try { await deletePocketTransaction(transaction.id); } finally { setRemovingId(null); } }; return <><section className="company-transaction-list"><div className="panel-heading"><div><p className="eyebrow">POCKET LEDGER</p><h2>Recent activity</h2></div><span className="progress-label">{transactions.length} total</span></div>{transactions.length ? <ul>{transactions.map((transaction) => { const isDebit = isPocketDebit(transaction.type); const goalName = transaction.savingsGoalId ? goalNames.get(transaction.savingsGoalId) : null; return <li key={transaction.id}><span className={`transaction-type pocket-${transaction.type}`}>{transactionLabels[transaction.type]}</span><div><strong>{transaction.note || 'No note added'}</strong><small>{formatDate(transaction.occurredOn)} · {goalName ? goalName : categoryLabels[transaction.category]}</small></div><b className={isDebit ? 'transaction-debit' : 'transaction-credit'}>{isDebit ? '−' : '+'}{formatCurrency(transaction.amount)}</b>{transaction.receiptDataUrl ? <button className="receipt-view-button" type="button" onClick={() => setViewingReceipt(transaction)}>Receipt</button> : null}<button className="remove-button" type="button" disabled={removingId === transaction.id} onClick={() => remove(transaction)} aria-label={`Remove ${transactionLabels[transaction.type]} entry`}>{removingId === transaction.id ? '…' : 'Remove'}</button></li>; })}</ul> : <div className="ledger-empty"><AppIcon name="wallet" aria-hidden="true" size={24} /><p>No pocket entries yet.</p><span>Record a cash movement to see it in your personal ledger.</span></div>}</section>{viewingReceipt?.receiptDataUrl ? <div className="receipt-dialog" role="dialog" aria-modal="true" aria-labelledby="receipt-title"><div><div className="receipt-dialog-heading"><h2 id="receipt-title">Receipt · {formatDate(viewingReceipt.occurredOn)}</h2><button className="remove-button" type="button" onClick={() => setViewingReceipt(null)}>Close</button></div><img src={viewingReceipt.receiptDataUrl} alt={`Receipt for ${formatCurrency(viewingReceipt.amount)} ${viewingReceipt.note ? `— ${viewingReceipt.note}` : ''}`} /></div></div> : null}</>; }

function SavingsGoalForm() { const [name, setName] = useState(''); const [targetAmount, setTargetAmount] = useState(''); const [savedAmount, setSavedAmount] = useState(''); const [targetDate, setTargetDate] = useState(''); const [note, setNote] = useState(''); const [status, setStatus] = useState(''); const [isSaving, setIsSaving] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const target = Number(targetAmount); const saved = savedAmount === '' ? 0 : Number(savedAmount); if (!name.trim() || !Number.isFinite(target) || target <= 0 || !Number.isFinite(saved) || saved < 0) { setStatus('Add a name, a target above zero, and a valid saved amount.'); return; } setIsSaving(true); setStatus(''); try { await addSavingsGoal({ name: name.trim(), targetAmount: target, savedAmount: saved, targetDate: targetDate || null, note: note.trim() }); setName(''); setTargetAmount(''); setSavedAmount(''); setTargetDate(''); setNote(''); setStatus('Savings goal created locally.'); } catch { setStatus('Could not create this savings goal. Please try again.'); } finally { setIsSaving(false); } }; return <form className="savings-goal-form" onSubmit={submit}><p className="eyebrow">NEW TARGET</p><label className="field"><span>Goal name</span><input value={name} maxLength={60} onChange={(event) => setName(event.target.value)} placeholder="Emergency fund" required /></label><div className="form-grid compact-form-grid"><label className="field"><span>Target (PKR)</span><input type="number" min="1" value={targetAmount} onChange={(event) => setTargetAmount(event.target.value)} placeholder="0" required /></label><label className="field"><span>Saved now (PKR)</span><input type="number" min="0" value={savedAmount} onChange={(event) => setSavedAmount(event.target.value)} placeholder="0" /></label></div><label className="field"><span>Target date</span><input type="date" value={targetDate} onChange={(event) => setTargetDate(event.target.value)} /></label><label className="field"><span>Note</span><input maxLength={100} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Optional reminder" /></label><div className="editor-actions"><span role="status">{status}</span><button className="secondary-button" type="submit" disabled={isSaving}>{isSaving ? 'Saving…' : 'Create goal'}</button></div></form>; }
function SavingsGoalCard({ goal }: { goal: SavingsGoal }) { const [savedAmount, setSavedAmount] = useState(String(goal.savedAmount)); const [status, setStatus] = useState(''); const [isSaving, setIsSaving] = useState(false); const percentage = Math.min(100, (goal.savedAmount / goal.targetAmount) * 100); const saveProgress = async () => { const nextSavedAmount = Number(savedAmount); if (!Number.isFinite(nextSavedAmount) || nextSavedAmount < 0) { setStatus('Enter a valid saved amount.'); return; } setIsSaving(true); setStatus(''); try { await updateSavingsGoal({ ...goal, savedAmount: nextSavedAmount }); setStatus('Progress saved.'); } catch { setStatus('Could not save progress.'); } finally { setIsSaving(false); } }; const remove = async () => { if (window.confirm(`Remove the ${goal.name} savings goal?`)) await deleteSavingsGoal(goal.id); }; return <article className="savings-goal-card"><div className="goal-card-heading"><div><strong>{goal.name}</strong><small>{goal.targetDate ? `Target: ${formatDate(goal.targetDate)}` : 'No target date'}</small></div><button className="remove-button" type="button" onClick={remove}>Remove</button></div><div className="goal-progress-copy"><span>{formatCurrency(goal.savedAmount)} saved</span><b>{Math.round(percentage)}%</b></div><progress value={Math.min(goal.savedAmount, goal.targetAmount)} max={goal.targetAmount}>{percentage}%</progress><p>{formatCurrency(Math.max(0, goal.targetAmount - goal.savedAmount))} remaining of {formatCurrency(goal.targetAmount)}</p>{goal.note ? <small className="goal-note">{goal.note}</small> : null}<div className="goal-update"><label className="field"><span>Saved amount (PKR)</span><input type="number" min="0" value={savedAmount} onChange={(event) => setSavedAmount(event.target.value)} /></label><button className="secondary-button" type="button" disabled={isSaving} onClick={saveProgress}>{isSaving ? 'Saving…' : 'Update'}</button></div><span className="field-status" role="status">{status}</span></article>; }
function SummaryCard({ label, amount, tone }: { label: string; amount: number; tone: 'credit' | 'debit' | 'neutral' }) { return <article><span>{label}</span><strong className={tone === 'credit' ? 'transaction-credit' : tone === 'debit' ? 'transaction-debit' : ''}>{formatCurrency(amount)}</strong><small>{tone === 'credit' ? 'recorded incoming' : tone === 'debit' ? 'recorded outgoing' : 'set aside'}</small></article>; }
function SetupRequired() { return <section className="feature-placeholder"><span className="placeholder-icon"><AppIcon name="wallet" aria-hidden="true" size={28} /></span><p className="eyebrow">PERSONAL POCKET</p><h1>Set up your workspace first.</h1><p>Your private pocket is ready after you complete the local salary setup.</p><Link className="primary-button" href="/onboarding">Start setup <AppIcon name="arrow-right" aria-hidden="true" size={17} /></Link></section>; }
function readReceipt(file: File): Promise<string> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(reader.error); reader.onload = () => typeof reader.result === 'string' ? resolve(reader.result) : reject(new Error('Receipt could not be read.')); reader.readAsDataURL(file); }); }
